id: AC4766658
base_file: f9D3E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 04:59:47.620872
  last_modified_at: 2022-05-31 04:59:47.620879
